version: '3'
services:
    app:
      image: node-front
      container_name: gambit-app-node
      build:
        context: .
        dockerfile: Dockerfile
      command: bash -c "npm install && npm run serve" 
      volumes:
        - .:/app
      ports:
        - "8080:8080"